[package]
name = "gameoflife"
version = "0.1.0"
authors = ["Tyler Holmes <tylerdanielholmes@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
term = "0.5"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termion = "1.5"